name: hypnettorch
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2023.05.30
  - certifi=2022.12.7
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - expat=2.4.9
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - jedi=0.18.1
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=4.11.2
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy-base=1.21.5
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.3.5
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - ply=3.11
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pycodestyle=2.10.0
  - pygments=2.11.2
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.7.16
  - python-dateutil=2.8.2
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.12.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - tensorboardx=2.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.4.0
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - future==0.18.3
    - hypnettorch==0.0.4
    - numpy==1.21.6
    - pillow==9.5.0
    - torch==1.5.0+cu101
    - torchsearchsorted==1.1
    - torchvision==0.6.0+cu101
